name: Code style
on:
  push:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Check code style
        run: vendor/bin/phpcs
