name: Test - PHP 7.3
on:
  push:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  call-test:
    uses: ./.github/workflows/test.yml
    with:
      php_version: 7.3
      phpunit_version: 9.5.20
